config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  # get 'vacancies/all' to: 'vacancies#all'
  authenticated :company do
    root to: 'vacancies#index', as: :company_root
  end
  unauthenticated :company do
    root to: 'vacancies#all', as: 'unauthenticated_root'
  end
  resources :applicants, only: :create
  resources :vacancies do
    resources :applicants, only: %i[index]
  end
  resources :vacancies
  # resources :companies
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :vacancy

  validates :name, presence: true

  has_one_attached :curriculum
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vacancies

  validates :name, presence: true
  validates :description, length: { minumum: 3, maximum: 1000 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :company
  has_many :applicants
  
  validates :title, presence: true
  validates :location, presence: true
  validates :description, length: { minumum: 3, maximum: 1000 }, presence: true
  validates :requirements, presence: true
  validates :salary, presence: true
  validates :available, presence: true

  include PgSearch::Model
  pg_search_scope :search, 
                  against: [:title, :location, :description, :requirements],
                  using: {
                    tsearch: { dictionary: "english", prefix: true } 
                  }
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  skip_before_action :authenticate_company!, only: :create
  before_action :set_applicant, only: %i[ show edit update destroy ]

  # GET /applicants or /applicants.json
  def index
    @vacancy = Vacancy.find(params[:vacancy_id])
    @applicants = Applicant.where(vacancy_id: params[:vacancy_id]).joins(:vacancy).where(@vacancy[company_id: current_company.id]).page(params[:page])
  end

  # GET /applicants/1 or /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants or /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to '/  ', notice: "You applied for the job!" } 
        format.json { render :show, status: :created, location: @applicant }
      else
        @vacancy = Vacancy.find(@applicant.vacancy_id)
        format.html { render "vacancies/show", status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1 or /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: "Applicant was successfully updated." }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1 or /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: "Applicant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def applicant_params
      params.require(:applicant).permit(:name, :vacancy_id, :curriculum, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_company!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name description])
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  skip_before_action :authenticate_company!, only:  %i[ show all ]
  before_action :set_vacancy, only: %i[ show edit update destroy ]

  # GET /vacancies or /vacancies.json
  def index
    if params[:query].present?
      @vacancies = Vacancy.search(params[:query]).page(params[:page])
    else
      @vacancies = current_company.vacancies.order(
        created_at: :desc
      ).page(params[:page])
    end
  end

  # GET /vacancies/1 or /vacancies/1.json
  def show
  end

  def all
    if params[:query].present?
      @vacancies = Vacancy.search(params[:query]).page(params[:page])
    else
      @vacancies = Vacancy.where(
        available: true
      ).order(created_at: :desc).page(params[:page])
    end
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new(available: true)
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies or /vacancies.json
  def create
    @vacancy = current_company.vacancies.build(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully created." }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1 or /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully updated." }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1 or /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: "Vacancy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacancy_params
      params.require(:vacancy).permit(:title, :location, :description, :requirements, :salary, :available, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applicants/_form.html.erb
<%= form_with(model: applicant, class: 'row g-3') do | form | %>
  <% if applicant.errors.any? %>
    <div id="error_explanation">
      <h2>  <%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
        <% applicant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-auto">
    <%= form.label 'Name', class: 'form-label', for: 'name' %>
    <%= form.text_field :name, class: 'form-control', id: 'name' %>
  </div>

  <div class="col-auto">
    <%= form.label 'Email', class: 'form-label', for: 'email' %>
    <%= form.email_field :email, class: 'form-control', id: 'email', autocomplete: 'email' %>
  </div>

  <div class="col-auto">
    <%= form.label 'CV', for:"curriculum", class: 'form-label' %>
    <%= form.file_field :curriculum, class: 'form-control', id: 'curriculum' %>
  </div>

  <div class="visually">
    <%= form.label 'Vacancy', for: 'vacancy' %>
    <%= form.text_field :vacancy_id %>
  </div>

  <div class="col-auto">
    <%= form.submit "Aplly", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<div class='container'>
  <%= link_to vacancies_path, :class => "icon-all my-5 text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>
  <h1 class='my-5'><%= @vacancy.title %></h1>

  <table class="table">
    <thead class='table-active th-text-color'>
      <tr>
        <th>Name</th>
        <th class='text-center'>Email</th>
        <th class='text-center'>Sent in</th>
        <th class='text-center'>Download CV</th>
      </tr>
    </thead>

    <tbody class='text-secondary'>
      <% @applicants.each do |applicant| %>
        <tr>
          <td class="align-middle"><%= applicant.name %></td>
          <td class="align-middle text-center"><%= applicant.email %></td>
          <td class="align-middle text-center"><%= applicant.created_at.strftime('%d/%m/%Y') %></td>
          <td class="align-middle text-center">
            <a href='<%= rails_blob_path(applicant.curriculum) if applicant.curriculum.attached? %>' target="_blank" class="text-primary text-decoration-none" aria-label="Left Align">
              <i class="fas fa-file-download fa-fw"></i>
            </a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex">
    <div class="mx-auto mt-5">
      <%= paginate @applicants, outer_window: 3, left: 1, right: 3 %>
    </div>
  </div>
</div>

app/views/applicants/new.html.erb
<h1>New Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @applicant.name %>
</p>

<p>
  <strong>Vacancy:</strong>
  <%= @applicant.vacancy_id %>
</p>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suche Jobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

   <body>
    <%= render "shared/navbar" %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<html>
  <head>
    <title>SucheJobs</title>
    <meta name="viewport" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <img src="/assets/SucheJobs.png" class="img-fluid logo" alt="SucheJobs logo" />
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a href= "/", class="nav-link" >All Vacancies</a>
      </li>
      <% unless company_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="/companies/sign_up">New Vacancy</a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/vacancies/new">New Vacancy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/vacancies">My Vacancies</a>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ms-auto">
        <% if company_signed_in? %>
          <li class="nav-item">
              <%= link_to('Edit Account', edit_company_registration_path(current_company), method: :get, class: 'nav-link') %>
            </li>
          <li class="nav-item">
            <%= link_to('Sign out', destroy_company_session_path, method: :delete, class: 'nav-link') %>
          </li>
        <% else %>
          <li class="nav-item">
              <a class="nav-link" href="/companies/sign_in">Sign in</a>
          </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/vacancies/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: vacancy) do |form| %>
      <% if vacancy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

          <ul>
            <% vacancy.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4">
        <%= form.label 'Title', class: 'form-label' %>

        <%= form.text_field :title, autofocus: true, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Location', class: 'form-label' %>

        <%= form.text_field :location, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Description', class: 'form-label' %>

        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Requirements', class: 'form-label' %>

        <%= form.text_area :requirements, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Salary', class: 'form-label' %>

        <%= form.text_field :salary, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.check_box :available, class: 'form-check-input', id: 'availableCheck' %>
        <%= form.label 'Available', class: "form-check-label", for: "availableCheck" %>

      </div>
      <div class="mb-4 mt-5">
        <%= form.submit "Save", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/vacancies/_vacancy_card.html.erb
<div class="vacancy-card card mb-5">
  <div class="card-header bg-white">
    <h5 class="card-title"> <%= vacancy.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"> <i class="fas fa-map-marker-alt"></i> <%= vacancy.location %></h6>
  </div>

  <div class="card-body">
    <p class="card-text"><%= vacancy.description %></p>

    <div class="row align-items-center">
      <div class="col-lg-6">
        <p class="card-text text-secondary">
          Posted <%= time_ago_in_words(vacancy.created_at) %> ago
        </p>
      </div>

      <div class="col-lg-6 align-self-end">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <a type="button" target="_blank" href="/vacancies/<%= vacancy.id %>">
            <i class="fas fa-eye icon-all"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vacancies/all.html.erb
<div class="container">
  <%= simple_form_for :search, url: '/', method: "GET", html: { class: 'form-inline mt-5 d-flex justify-content-end' } do |f| %>
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a vacancy" %> 
    <%= button_tag type: 'submit', class: "btn btn-primary", id: "register-button" do %> 
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>

  <h1 class="my-5">Vacancies</h1>

  <div class="row">
    <div class="col-lg-12">
      <% @vacancies.each do |vacancy| %>
        <%= render partial: 'vacancy_card', locals: { vacancy: vacancy } %>
      <% end %>
    </div>
  </div>

  <div class="d-flex">
    <div class="mx-auto mt-5">
      <%= paginate @vacancies, outer_window: 3, left: 1, right: 3 %>
    </div>
  </div>

</div>

app/views/vacancies/edit.html.erb
<div class="container">
  <%= link_to vacancies_path, :class => "icon-all my-5 text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <div class="bg-white rounded p-3 shadow mt-5">
    <div class="p-5">
      <h1>Editing Vacancy</h1>

      <%= render 'form', vacancy: @vacancy %>
    </div>
  </div>
</div>

app/views/vacancies/index.html.erb
<div class="container mb-5">
  <%= simple_form_for :search, url: vacancies_path, method: "GET", html: { class: 'form-inline mt-5 d-flex justify-content-end' } do |f| %>
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a vacancy" %> 
    <%= button_tag type: 'submit', class: "btn btn-primary", id: "register-button" do %> 
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>

  <h1 class="m-5">Vacancies</h1>

  <table class="table">
    <thead class="table-active">
      <tr>
        <th>Vacancy</th>
        <th>Creation date</th>
        <th>Applicants</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody class="text-secondary">
      <% @vacancies.each do |vacancy| %>
        <tr>
          <td class="align-middle"><%= vacancy.title %></td>
          <td class="align-middle"><%= vacancy.created_at.strftime('%d/%m/%Y') %></td>
          <td class="align-middle"><%= vacancy.applicants.count %></td>
          <td class="align-middle">
            <%= link_to edit_vacancy_path(vacancy), class: "text-primary text-decoration-none mr-4" do %>
              <i class="far fa-edit"></i> Edit
            <% end %>
            <a href="/vacancies/<%= vacancy.id %>/applicants" class="text-primary text-decoration-none">
              <i class="far fa-user"></i> Applicants
            </a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex">
    <div class="mx-auto mt-5">
      <%= paginate @vacancies, outer_window: 3, left: 1, right: 3  %>   
    </div>
  </div>
  <br>

  <%= link_to 'New Vacancy', new_vacancy_path, class: 'btn btn-primary' %>
</div>

app/views/vacancies/new.html.erb
<div class="container">
  <%= link_to vacancies_path, :class => "icon-all my-5 text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>


  <div class="bg-white rounded p-3 shadow mt-5">
    <div class="p-5">
      <h1>New Vacancy</h1>

      <%= render 'form', vacancy: @vacancy %>
    </div>
  </div>
</div>

app/views/vacancies/show.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col-md-7 col-sm-12">
      <h1 class="mb-4"> <%= @vacancy.title %></h1>

      <div class="my-5">
        <p class="text-secondary"> <%= @vacancy.description %></p>
        <p class="text-secondary"> <i class="fas fa-map-marker-alt"></i> <%= @vacancy.location %></p>
      </div>

      <div class="my-5">
        <h3>Requirements:</h3>
        <p class="text-secondary"> <%= @vacancy.requirements %></p>
      </div>

      <h3 class="my-5">Salary: <span class="text-secondary"><%= @vacancy.salary %></span></h3>
      <%# <p class="text-secondary"> </p> %>
    </div>
    <div class="col-md-4 offset-md-1 card">
      <h3 class="mt-4 mb-4 text-center">Company</h2>
      <h5 class="mt-4 mb-2"><i class="fas fa-building"></i> <%= @vacancy.company.name %></h3>
      <p class="text-secondary"> <%= @vacancy.company.description %></p>
    </div>
    
    <div class="col-md-10">
      <hr class="mt-5 mb-5">
      <h3 class="my-4">Aplly now:</h3>
      <%= render partial: 'applicants/form', locals: { applicant: @applicant || Applicant.new(vacancy_id: @vacancy.id) } %>
    </div>
  </div>
  
</div>